/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Options accepted from JS. All fields mirror `PluginOptions` on the TS side. */
export interface ComputeOptions {
  root: string
  include: Array<string>
  length: number
}

/**
 * Compute a deterministic hex hash of matched i18n files.
 *
 * Returns the truncated hex string (length chars).
 */
export declare function computeVersion(opts: ComputeOptions): string
